server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allow-credentials: true
      routes:
        
        - id: vehiculo-service
          uri: lb://vehiculo-service:8091
          predicates:
            - Path=/api/v1/vehiculo/**
        - id: precio-por-rep-service
          uri: lb://precio-por-rep-service:8092
          predicates:
            - Path=/api/v1/precioPorRep/**
        - id: ingreso-service
          uri: lb://ingreso-service:8093
          predicates:
            - Path=/api/v1/ingresoAReparacion/**