server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-orders
          uri: lb://ms-orders:8090
          predicates:
            - Path=/orders/**
        - id: vehiculo-service
          uri: lb://vehiculo-service:8091
          predicates:
            - Path=/api/v1/vehiculo/**
        - id: precio-por-rep-service
          uri: lb://precio-por-rep-service:8092
          predicates:
            - Path=/api/v1/precioPorRep/**