server:
  port: 8092
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/precio-por-rep-bd
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka