server:
  port: 8091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/basededatos-ms
    username: postgres
    password: password
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka